bil_site_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('nbil/', include('nbil.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

nbil/urls.py
from django.urls import path

from . import views


app_name='nbil'
urlpatterns = [
    path('', views.index, name='index'),

    path('ur_list', views.ur_list, name='ur_list'),
    path('ur_list/edit<int:urid>/', views.edit, name='uredit'),
    path('ur_list/info<int:urid>/', views.info, name='urinfo'),
    path('ur_list/create_UR/', views.UR_create, name='urcreate'),

	path('conn_list/', views.connlist, name='connlist'),
    path('conn_list/edit<int:urid>/', views.connedit, name='connedit'),
    path('conn_list/create_conn/', views.createconn, name='conncreate'),


    path('tariff/', views.add_tariff, name='tariff'),
    path('zone/', views.add_zone, name='zone'),
    path('CSB_import/', views.add_CSB_data, name='CSB_import'),
    path('CSPR_data/', views.get_skome_data, name='CSPRdata'),


]

nbil/models.py
from django.db import models
from django.conf import settings
from django.db.models import Count


class tariff_data(models.Model):
	tariff_date=models.DateField()
	tariff_schemas=models.CharField(max_length=5)
	hour_1=models.FloatField()
	hour_2=models.FloatField()
	hour_3=models.FloatField()
	hour_4=models.FloatField()
	hour_5=models.FloatField()
	hour_6=models.FloatField()
	hour_7=models.FloatField()
	hour_8=models.FloatField()
	hour_9=models.FloatField()
	hour_10=models.FloatField()
	hour_11=models.FloatField()
	hour_12=models.FloatField()
	hour_13=models.FloatField()
	hour_14=models.FloatField()
	hour_15=models.FloatField()
	hour_16=models.FloatField()
	hour_17=models.FloatField()
	hour_18=models.FloatField()
	hour_19=models.FloatField()
	hour_20=models.FloatField()
	hour_21=models.FloatField()
	hour_22=models.FloatField()
	hour_23=models.FloatField()
	hour_24=models.FloatField()

	def __str__(self):
		return self.name

	@classmethod
	def save_file(cls, deff, data, tar):
		tariff_data.objects.update_or_create( 
			defaults=deff, tariff_date=data, tariff_schemas=tar)

class zone_data(models.Model):
	zone_date=models.DateField()
	zone_schemas=models.CharField(max_length=5)
	hour_1=models.IntegerField()
	hour_2=models.IntegerField()
	hour_3=models.IntegerField()
	hour_4=models.IntegerField()
	hour_5=models.IntegerField()
	hour_6=models.IntegerField()
	hour_7=models.IntegerField()
	hour_8=models.IntegerField()
	hour_9=models.IntegerField()
	hour_10=models.IntegerField()
	hour_11=models.IntegerField()
	hour_12=models.IntegerField()
	hour_13=models.IntegerField()
	hour_14=models.IntegerField()
	hour_15=models.IntegerField()
	hour_16=models.IntegerField()
	hour_17=models.IntegerField()
	hour_18=models.IntegerField()
	hour_19=models.IntegerField()
	hour_20=models.IntegerField()
	hour_21=models.IntegerField()
	hour_22=models.IntegerField()
	hour_23=models.IntegerField()
	hour_24=models.IntegerField()

	def __str__(self):
		return self.name

	@classmethod
	def save_file(cls, deff, data, tar):
		zone_data.objects.update_or_create( 
			defaults=deff, zone_date=data, zone_schemas=tar)


class UR_objects(models.Model):
	URB=((0, "POB"),
		(1, "SE")
		)
	code=models.CharField(max_length=25)
	name=models.CharField(max_length=70)
	is_pob=models.IntegerField(choices=URB, default=0)
	DT_create=models.DateField(auto_now_add=True)
	user=models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET('deleted'))
	DT_modify=models.DateField(auto_now=True)

	def __str__(self):
		return self.name

class UR_conn(models.Model):
	POB=models.ForeignKey(UR_objects, related_name='POB_id', on_delete=models.CASCADE)
	SE=models.ForeignKey(UR_objects, related_name='SE_id', on_delete=models.CASCADE)
	DT_from=models.DateField()
	DT_to=models.DateField()
	DT_create=models.DateField(auto_now_add=True)
	user=models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET('deleted'), null=True)
	DT_modify=models.DateField(auto_now=True)
	
	def __str__(self):
		return self.name


class CSPR_data(models.Model):
	PPE_number=models.CharField(max_length=40)
	month_date=models.IntegerField()
	year_date=models.IntegerField()
	value_d1=models.FloatField(null=True)
	value_d2=models.FloatField(null=True)
	value_d3=models.FloatField(null=True)
	value_d4=models.FloatField(null=True)
	value_d5=models.FloatField(null=True)
	value_d6=models.FloatField(null=True)
	value_d7=models.FloatField(null=True)
	value_d8=models.FloatField(null=True)
	value_d9=models.FloatField(null=True)
	value_d10=models.FloatField(null=True)
	value_d11=models.FloatField(null=True)
	value_d12=models.FloatField(null=True)
	value_d13=models.FloatField(null=True)
	value_d14=models.FloatField(null=True)
	value_d15=models.FloatField(null=True)
	value_d16=models.FloatField(null=True)
	value_d17=models.FloatField(null=True)
	value_d18=models.FloatField(null=True)
	value_d19=models.FloatField(null=True)
	value_d20=models.FloatField(null=True)
	value_d21=models.FloatField(null=True)
	value_d22=models.FloatField(null=True)
	value_d23=models.FloatField(null=True)
	value_d24=models.FloatField(null=True)
	value_d25=models.FloatField(null=True)
	value_d26=models.FloatField(null=True)
	value_d27=models.FloatField(null=True)
	value_d28=models.FloatField(null=True)
	value_d29=models.FloatField(null=True)
	value_d30=models.FloatField(null=True)
	value_d31=models.FloatField(null=True)
	status_d1=models.IntegerField(null=True)
	status_d2=models.IntegerField(null=True)
	status_d3=models.IntegerField(null=True)
	status_d4=models.IntegerField(null=True)
	status_d5=models.IntegerField(null=True)
	status_d6=models.IntegerField(null=True)
	status_d7=models.IntegerField(null=True)
	status_d8=models.IntegerField(null=True)
	status_d9=models.IntegerField(null=True)
	status_d10=models.IntegerField(null=True)
	status_d11=models.IntegerField(null=True)
	status_d12=models.IntegerField(null=True)
	status_d13=models.IntegerField(null=True)
	status_d14=models.IntegerField(null=True)
	status_d15=models.IntegerField(null=True)
	status_d16=models.IntegerField(null=True)
	status_d17=models.IntegerField(null=True)
	status_d18=models.IntegerField(null=True)
	status_d19=models.IntegerField(null=True)
	status_d20=models.IntegerField(null=True)
	status_d21=models.IntegerField(null=True)
	status_d22=models.IntegerField(null=True)
	status_d23=models.IntegerField(null=True)
	status_d24=models.IntegerField(null=True)
	status_d25=models.IntegerField(null=True)
	status_d26=models.IntegerField(null=True)
	status_d27=models.IntegerField(null=True)
	status_d28=models.IntegerField(null=True)
	status_d29=models.IntegerField(null=True)
	status_d30=models.IntegerField(null=True)
	status_d31=models.IntegerField(null=True)
	tariff_d1=models.CharField(max_length=6, null=True)
	tariff_d2=models.CharField(max_length=6, null=True)
	tariff_d3=models.CharField(max_length=6, null=True)
	tariff_d4=models.CharField(max_length=6, null=True)
	tariff_d5=models.CharField(max_length=6, null=True)
	tariff_d6=models.CharField(max_length=6, null=True)
	tariff_d7=models.CharField(max_length=6, null=True)
	tariff_d8=models.CharField(max_length=6, null=True)
	tariff_d9=models.CharField(max_length=6, null=True)
	tariff_d10=models.CharField(max_length=6, null=True)
	tariff_d11=models.CharField(max_length=6, null=True)
	tariff_d12=models.CharField(max_length=6, null=True)
	tariff_d13=models.CharField(max_length=6, null=True)
	tariff_d14=models.CharField(max_length=6, null=True)
	tariff_d15=models.CharField(max_length=6, null=True)
	tariff_d16=models.CharField(max_length=6, null=True)
	tariff_d17=models.CharField(max_length=6, null=True)
	tariff_d18=models.CharField(max_length=6, null=True)
	tariff_d19=models.CharField(max_length=6, null=True)
	tariff_d20=models.CharField(max_length=6, null=True)
	tariff_d21=models.CharField(max_length=6, null=True)
	tariff_d22=models.CharField(max_length=6, null=True)
	tariff_d23=models.CharField(max_length=6, null=True)
	tariff_d24=models.CharField(max_length=6, null=True)
	tariff_d25=models.CharField(max_length=6, null=True)
	tariff_d26=models.CharField(max_length=6, null=True)
	tariff_d27=models.CharField(max_length=6, null=True)
	tariff_d28=models.CharField(max_length=6, null=True)
	tariff_d29=models.CharField(max_length=6, null=True)
	tariff_d30=models.CharField(max_length=6, null=True)
	tariff_d31=models.CharField(max_length=6, null=True)
	SE=models.CharField(max_length=30)
	user=models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET('deleted'))
	DT_modify=models.DateField(auto_now=True)


	@classmethod
	def save_cspr_obj(cls, ppe, year, month, SE, obj):
		CSPR_data.objects.update_or_create(defaults=obj, PPE_number=ppe, year_date=year, month_date=month, SE=SE)

	@classmethod
	def save_data(cls, deff):
		CSPR_data.objects.bulk_create(deff)

class CSB_data(models.Model):
	PPE_number=models.CharField(max_length=40)
	year_date=models.IntegerField(default=1999)
	month_date=models.IntegerField(default=1)
	value_d1=models.FloatField(null=True, default=0)
	value_d2=models.FloatField(null=True, default=0)
	value_d3=models.FloatField(null=True, default=0)
	value_d4=models.FloatField(null=True, default=0)
	value_d5=models.FloatField(null=True, default=0)
	value_d6=models.FloatField(null=True, default=0)
	value_d7=models.FloatField(null=True, default=0)
	value_d8=models.FloatField(null=True, default=0)
	value_d9=models.FloatField(null=True, default=0)
	value_d10=models.FloatField(null=True, default=0)
	value_d11=models.FloatField(null=True, default=0)
	value_d12=models.FloatField(null=True, default=0)
	value_d13=models.FloatField(null=True, default=0)
	value_d14=models.FloatField(null=True, default=0)
	value_d15=models.FloatField(null=True, default=0)
	value_d16=models.FloatField(null=True, default=0)
	value_d17=models.FloatField(null=True, default=0)
	value_d18=models.FloatField(null=True, default=0)
	value_d19=models.FloatField(null=True, default=0)
	value_d20=models.FloatField(null=True, default=0)
	value_d21=models.FloatField(null=True, default=0)
	value_d22=models.FloatField(null=True, default=0)
	value_d23=models.FloatField(null=True, default=0)
	value_d24=models.FloatField(null=True, default=0)
	value_d25=models.FloatField(null=True, default=0)
	value_d26=models.FloatField(null=True, default=0)
	value_d27=models.FloatField(null=True, default=0)
	value_d28=models.FloatField(null=True, default=0)
	value_d29=models.FloatField(null=True, default=0)
	value_d30=models.FloatField(null=True, default=0)
	value_d31=models.FloatField(null=True, default=0)
	tariff_d1=models.CharField(max_length=6, null=True)
	tariff_d2=models.CharField(max_length=6, null=True)
	tariff_d3=models.CharField(max_length=6, null=True)
	tariff_d4=models.CharField(max_length=6, null=True)
	tariff_d5=models.CharField(max_length=6, null=True)
	tariff_d6=models.CharField(max_length=6, null=True)
	tariff_d7=models.CharField(max_length=6, null=True)
	tariff_d8=models.CharField(max_length=6, null=True)
	tariff_d9=models.CharField(max_length=6, null=True)

nbil/forms.py
from django import forms
from .models import UR_objects, UR_conn, tariff_data


class Conn_form(forms.ModelForm):

	POB = forms.ModelChoiceField(queryset=UR_objects.objects.filter(is_pob=0), to_field_name = 'name')
	SE = forms.ModelChoiceField(queryset=UR_objects.objects.filter(is_pob=1), to_field_name = 'name')
	DT_to = forms.DateField(widget=forms.TextInput(attrs={'class':'datepicker'}))
	class Meta:
		model = UR_conn
		exclude = ['user_id']
		#'DT_to' = forms.DateField(widget=forms.TextInput(attrs={'class':'datepicker'}))

class UR_edit_form(forms.ModelForm):
	class Meta:
		model=UR_objects
		exclude = ['user_id']


class UR_form_create(forms.ModelForm):
	class Meta:
		model=UR_objects
		fields = ['code', 'name', 'is_pob']


class conn_edit_form(forms.ModelForm):

	#POB = forms.ModelChoiceField(queryset=UR_objects.objects.filter(id=1), to_field_name = 'name')
	#SE = forms.ModelChoiceField(queryset=UR_objects.objects.filter(is_pob=1), to_field_name = 'code')
	
	class Meta:
		model=UR_conn
		fields = ['POB', 'SE', 'DT_from', 'DT_to']


class UploadFileForm(forms.Form):
	file = forms.FileField()


class CSPRimportdate(forms.Form):
    date = forms.DateTimeField(input_formats=['%Y-%m%d %H:%M'])

nbil/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404, redirect
from django.views.generic.edit import CreateView
from django.contrib.auth.decorators import login_required
from tablib import Dataset

from django.http import HttpResponse
from .models import UR_objects, UR_conn
from .forms import Conn_form, UR_edit_form, conn_edit_form, UR_form_create, UploadFileForm
from .filters import URFilter, ConnFilter
from .services import import_ELZ, import_ELP, import_csb_data, CSB_decompose, cspr_handle

import cx_Oracle

@login_required
def index(request):
	ob_list = UR_objects.objects.all()[:6]
	context = {'kutasy': ob_list}
	return render(request, 'nbil/nbil_index.html', context)

@login_required
def ur_list(request):
	#urlist=get_list_or_404(UR_objects)
	urlist = UR_objects.objects.all()
	fil=UR_objects.objects.all()
	filtrrr=URFilter(request.GET, queryset=fil)
	context={'filtrrr':filtrrr, 'urlist':urlist}
	return render(request, 'nbil/ur_list.html', context)

@login_required
def edit(request, urid):
	ob = get_object_or_404(UR_objects, pk=urid)
	if request.method=='POST':
		form=UR_edit_form(request.POST, instance=ob)
		if form.is_valid():
			form.save()
			return redirect('nbil:ur_list')
	else:
		form=UR_edit_form(instance=ob)
	context={'form':form, 'ob':ob}
	return render(request, 'nbil/uredit.html', context)

@login_required
def info(request, urid):
	element=get_object_or_404(UR_objects, id=urid)
	
	connspob=UR_conn.objects.filter(POB_id=urid)
	connsse=UR_conn.objects.filter(SE_id=urid)
	context={'element':element, 'connspob':connspob, 'connsse':connsse}
	return render(request, 'nbil/urinfo.html', context)

@login_required
def connlist(request):
	lista = UR_conn.objects.all()
	fil=UR_conn.objects.all()
	filtrrr=ConnFilter(request.GET, queryset=fil)
	context={'filtrrr':filtrrr, 'lista':lista}
	return render(request, 'nbil/connlist.html', context)

@login_required
def connedit(request, urid):
	ob = get_object_or_404(UR_conn, pk=urid)
	if request.method=='POST':
		form=conn_edit_form(request.POST, instance=ob)
		if form.is_valid():
			form.save()
			return redirect('nbil:ur_list')
	else:
		form=conn_edit_form(instance=ob)
	context={'form':form, 'ob':ob}
	return render(request, 'nbil/connedit.html', context)

@login_required
def createconn(request):
	if request.method=='POST':
		form=Conn_form(request.POST)
		if form.is_valid():
			newConn=form.save(commit=False)
			newConn.user_id=request.user.id
			newConn.save()
			return redirect('nbil:connlist')
	else:
		form=Conn_form()
	context={'form':form}
	return render(request, 'nbil/conncreate.html', context)


@login_required
def UR_create(request):
	username=request.user
	if request.method=='POST':
		form=UR_form_create(request.POST)
		if form.is_valid():
			newUR=form.save(commit=False)
			newUR.user_id=request.user.id
			newUR.save()
			return redirect('nbil:ur_list')
	else:
		form=UR_form_create()
	context={'form':form, 'username':username}
	return render(request, 'nbil/urcreate.html', context)


@login_required
def add_tariff(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            import_ELP(request.FILES['file'])

    else:
        form = UploadFileForm()
    return render(request, 'nbil/addtariff.html', {'form': form})

	

@login_required
def add_zone(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            import_ELZ(request.FILES['file'])

    else:
        form = UploadFileForm()
    return render(request, 'nbil/addzone.html', {'form': form})


@login_required
def add_CSB_data(request):
    user_data = request.user
    #zz=current_user.id
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            import_csb_data(request.FILES['file'])
            #CSB_decompose(user_data)
    else:
        form = UploadFileForm()

    return render(request, 'nbil/addCSB.html', {'form': form})


@login_required
def get_skome_data(request):
	user_data = request.user
	cspr_handle(user_data)
	return render(request, 'nbil/CSPRdata.html')

nbil/templates/nbil/CSPRdata.html
{% extends "nbil/base_generic.html" %}
{% block content %}

{{ form.date }}

<script>
  $(function () {
    $("#id_date").datepicker({
      format:'yyyy-mm-dd',
    });
  });
</script>


{% endblock %}
<!-- 

<form action="{% url 'downloadexcel' %}" method="post">
{% csrf_token %}


 <button type="submit" name='mybtn2' value={{excel_path}}>get data</button>
 </form>
 -->

nbil/templates/nbil/addCSB.html
{% extends "nbil/base_generic.html" %}
{% block content %}

  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    
    <button type="submit">Upload</button>
  </form>


{% endblock %}

nbil/templates/nbil/addtariff.html
{% extends "nbil/base_generic.html" %}
{% block content %}

  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Upload</button>
  </form>
{% endblock %}

nbil/templates/nbil/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
	{% block title %}<title>aaaaN1111111sdfd</title>{% endblock %}
	{% load static %}
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static 'nbil/style.css.' %}">

 
</head>
<body>


<div class="menu"></div>


	<div class="page">	

	
	
		<div class="sidebar">
		<a href="{% url 'nbil:connlist' %}">Połączenia</a>
		<a href="{% url 'nbil:ur_list' %}">Użytkownicy rynku</a>
		<a href="{% url 'nbil:tariff' %}">Schematy taryfowe</a>
		<a href="{% url 'nbil:zone' %}">Strefy</a>
		<a href="{% url 'nbil:CSB_import' %}">Dane SKOK-D</a>
		<a href="{% url 'nbil:CSPRdata' %}">Dane Innop</a>

		</div>

		<div class="main">
    	{% block content %}{% endblock %}
		</div>


	</div>

	<div class='footer'>
	
	<p>create by</p>
	<p>home</p>

	</div>

	

	

</body>
</html>

nbil/templates/nbil/conncreate.html
{% extends "nbil/base_generic.html" %}
{% block content %}
<p>Dodaj nowe połączenie</p>

  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Upload</button>
  </form>

</form>

{% endblock %}

nbil/templates/nbil/connedit.html
{% extends "nbil/base_generic.html" %}
{% block content %}
<p>ID obiektu: {{ob.id}}</p>

<form action="{% url 'nbil:connedit' ob.id %}" method="POST">
{% csrf_token %}
{{form.as_p}}

<input type="submit" value="Edytuj">
</form>
{% endblock %}

nbil/templates/nbil/connlist.html
{% extends "nbil/base_generic.html" %}
{% block content %}
<p>Lista połączeń POB-SE</p>

<div class='add_button'>
<a class="btn btn-primary btn-sm" href="{% url 'nbil:conncreate' %}" role="button">+ Dodaj Połączenie</a>
</div>

<form method="get">
    {{ filtrrr.form.as_table }}
    <button type="submit">Szukaj</button>
</form>


<table class='table'>
		<tr>
			<th>ID</th>
			<th>Początek</th>
			<th>Koniec</th>
			<th>POB</th>
			<th>SE</th>
			<th>Utworzono</th>
			<th>Edytuj</th>
		</tr>
	{%for l in filtrrr.qs %}
		<tr>
			<td>{{l.id}}</td>
			<td>{{l.DT_from}}</td>
			<td>{{l.DT_to}}</td>
			<td><a href="{% url 'nbil:urinfo' l.id %}">{{l.POB.name}}</a></td>
			<td><a href="{% url 'nbil:urinfo' l.id %}">{{l.SE.name}}</a></td>
			<td>{{l.DT_create}}</td>
			<td><a class="btn btn-primary btn-sm" href="{% url 'nbil:connedit' l.id %}" role="button">Edytuj</a></td>
		</tr>
	{% empty %}
		<p>as</p>

	{%endfor%}
	


</table>


{%endblock%}

nbil/templates/nbil/edit.html
{% extends "nbil/base_generic.html" %}
{% block content %}
<p>kod: {{ob.code}}</p>



<form action="{% url 'nbil:uredit' ob.id %}" method="POST">
{% csrf_token %}
{{form.as_p}}
<input type="submit" value="Edit">

</form>




<h1>asd</h1>
{% endblock %}

nbil/templates/nbil/info.html
{% extends "nbil/base_generic.html" %}
{% block content %}

<p>Informacje na temat UR</p>

	<li>Index: {{element.id}}</li>
	<li>Kod: {{element.code}}</li>
	<li>Nazwa: {{element.name}}</li>
	<li>Stoworzono: {{element.DT_create}}</li>
	<li>Ostatnia modyfikacja: {{element.DT_modify}}</li>
	{% if element.is_pob %}
	<li>Typ: SE</li>
	{%else%}
	<li>Typ: POB</li>
	{%endif%}

	<li>Utworzył: {{element.user.username}}</li>


<p>Lista połczeń dotyczcych UR</p>

<table class="table table-condensed">
	<tr>
		<th>ID</th>
		<th>Data od</th>
		<th>Data do</th>
		<th>POB</th>
		<th>SE</th>

	</tr>
{% for i in connsse %}
	<tr>
		<td>{{i.id}}</td>
		<td>{{i.DT_from}}</td>
		<td>{{i.DT_to}}</td>
		<td>{{i.POB.name}}</td>
		<td>{{i.SE.name}}</td>
	</tr>
{%endfor%}
{% for i in connspob %}
	<tr>
		<td>{{i.id}}</td>
		<td>{{i.DT_from}}</td>
		<td>{{i.DT_to}}</td>
		<td>{{i.POB.name}}</td>
		<td>{{i.SE.name}}</td>
	</tr>
{%endfor%}





</table>
{%endblock%}

nbil/templates/nbil/nbil_index.html
{% extends "nbil/base_generic.html" %}
{% block content %}

<p>Pierwsza strona niezbilansowania, nawiguj dalej</p>

{% endblock %}

nbil/templates/nbil/ur_list.html
{% extends "nbil/base_generic.html" %}
{% block content %}

<div class='add_button'>
<a class="btn btn-primary btn-sm" href="{% url 'nbil:urcreate' %}" role="button">+ Dodaj UR</a>
</div>

<form method="get">
    {{ filtrrr.form.as_table }}
    <button type="submit">Search</button>
</form>

<h1>Lista POB</h1>
	<table class="table">
		<tr>
			<th>ID</th>
			<th>name</th>
			<th>code</th>
			<th>Edytuj</th>
			<th>Przejdź</th>
		</tr>
		{% for pob in filtrrr.qs %}
		<tr>
			
			<td>{{pob.id}}</td>
			<td>{{pob.name}}</td>
			<td>{{pob.code}}</td>
			<td><a class="btn btn-primary btn-sm" href="{% url 'nbil:uredit' pob.id %}" role="button">Edit</a></td>
			<td><a class="btn btn-primary btn-sm" href="{% url 'nbil:urinfo' pob.id %}" role="button">Info</a></td>
		{% endfor %}	
		</tr>
		
	</table>

{% endblock %}

nbil/templates/nbil/urcreate.html
{% extends "nbil/base_generic.html" %}
{% block content %}
<p>Stwórz nowego użytkownika rynku</p>
<p>Zalogowany jako: {{username}}</p>


<form action="{% url 'nbil:urcreate' %}" method="POST">
{% csrf_token %}
{{form.as_p}}
<input type="submit" value="Dodaj">

</form>

{% endblock %}

nbil/templates/nbil/uredit.html
{% extends "nbil/base_generic.html" %}
{% block content %}
<p>kod: {{ob.code}}</p>



<form action="{% url 'nbil:uredit' ob.id %}" method="POST">
{% csrf_token %}
{{form.as_p}}
<input type="submit" value="Edit">

</form>

{% endblock %}

nbil/templates/nbil/urinfo.html
{% extends "nbil/base_generic.html" %}
{% block content %}

<p>Informacje na temat UR</p>

	<li>Index: {{element.id}}</li>
	<li>Kod: {{element.code}}</li>
	<li>Nazwa: {{element.name}}</li>
	<li>Stoworzono: {{element.DT_create}}</li>
	<li>Ostatnia modyfikacja: {{element.DT_modify}}</li>
	{% if element.is_pob %}
	<li>Typ: SE</li>
	{%else%}
	<li>Typ: POB</li>
	{%endif%}

	<li>Utworzył: {{element.user.username}}</li>


<p>Lista połczeń dotyczcych UR</p>

<table class="table table-condensed">
	<tr>
		<th>ID</th>
		<th>Data od</th>
		<th>Data do</th>
		<th>POB</th>
		<th>SE</th>

	</tr>
{% for i in connsse %}
	<tr>
		<td>{{i.id}}</td>
		<td>{{i.DT_from}}</td>
		<td>{{i.DT_to}}</td>
		<td>{{i.POB.name}}</td>
		<td>{{i.SE.name}}</td>
	</tr>
{%endfor%}
{% for i in connspob %}
	<tr>
		<td>{{i.id}}</td>
		<td>{{i.DT_from}}</td>
		<td>{{i.DT_to}}</td>
		<td>{{i.POB.name}}</td>
		<td>{{i.SE.name}}</td>
	</tr>
{%endfor%}





</table>
{%endblock%}